CFLAGS = -I /source/samtools-0.1.18 -L /source/samtools-0.1.18 -lbam -lz

bamstat: bamstat.cpp alignment_stats.o running_mean.o running_median.o read_pair.o
	g++ -O3 -o bamstat bamstat.cpp alignment_stats.o running_mean.o running_median.o read_pair.o $(CFLAGS)

alignment_stats.o: alignment_stats.cpp
	g++ -O3 -c alignment_stats.cpp -I /usr/local/src/samtools-0.1.18

running_mean.o: running_mean.cpp
	g++ -O3 -c running_mean.cpp

running_median.o: running_median.cpp
	g++ -O3 -c running_median.cpp

read_pair.o: read_pair.cpp
	g++ -O3 -c read_pair.cpp -I /usr/local/src/samtools-0.1.18

clean:
	rm *.o
	rm bamstat
